language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer install
  - sleep 10

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit tests --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v